### ISSUE TITLE
Chinese characters inside script tag breaking

### ISSUE THREAD

**Issue by gijo-varghese** [Imangazaliev/DiDOM#167]
```php
<?php

require_once 'vendor/autoload.php';

$html = <<<EOD
<!DOCTYPE html>
<html>
    <head>
        <script>
            const str = "訂閱最新指南";
        </script>
    </head>
    <body>
    </body>
</html>
EOD;

$doc = new \DiDom\Document();
$doc->loadHTML($html);
echo $doc->html();
```

Will result in:
```html
<!DOCTYPE html>
<html>
    <head>
        <script>
            const str = "&#35330;&#38321;&#26368;&#26032;&#25351;&#21335;";
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by gijo-varghese** [comment]
And also this one:
```css
<style>
  body {
    background-image: url('https://example.com/örebro.jpg');
  }
</style>
```
